name: chess_clock
description: A chess clock
# Version 2.2 of the code number number 2.
version: 2.2.0+2
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_launcher_icons: ^0.9.2
  launch_review: ^3.0.1
  provider: ^6.0.1
  vibration: ^1.7.3
  shared_preferences: ^2.0.8
  flutter_picker: ^2.0.2
  easy_localization: ^3.0.0
#  google_mobile_ads: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icons/chess.png
flutter:
  uses-material-design: true
  assets:
    - assets/icons/chess.png
    - assets/translations/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700